{["/" [:cmd]] "commentThing:"
 ["q" [:alt]] "indentSection:"
 ["r" [:alt]] "raiseSexp:"
 ["k" [:ctrl :alt]] "killNextSexp:"
 ["s" [:alt]] "spliceSexp:"
 ["b" [:ctrl :alt]] "backwardSexp:"
 ["f" [:ctrl :alt]] "forwardSexp:"
 ["d" [:ctrl :alt]] "inForwardSexp:"
 ["p" [:ctrl :alt]] "inBackwardSexp:"
 ["u" [:ctrl :alt]] "outBackwardSexp:"
 ["n" [:ctrl :alt]] "outForwardSexp:"
 ["m" [:alt]] "jumpToFirstNonBlankCharacterOnLine:"
 [" " [:ctrl :alt]] "extendSelectionToNext:"
 ["9" [:ctrl]] "wrapNextInParens:"
 ["[" [:ctrl]] "wrapNextInBrackets:"
 ["{" [:ctrl]] "wrapNextInBraces:"
 ["}" [:alt]] "jumpToNextBlankLineGroup:"
 ["{" [:alt]] "jumpToPreviousBlankLineGroup:"}